### PR TITLE
feat: delete generate files and move migration folder to root

### PR DESCRIPTION
**Pull request by Tsugami**
go folder is generated files in development and should not be uploaded

to generate these files, just run `go run` on Erupe

### CODE REVIEW

**Comment by Tsugami** [comment]
also this folder is making the repository slow to clone and to develop

**Review by JVictorV — APPROVED** [review]
LGTM!

**Comment by xl3lackout** [comment]
Thanks for the heads up. I just uploaded what I had and we've developed on it since. I hadn't really considered what files were actually prudent or not.

**Comment by Tsugami** [comment]
> Thanks for the heads up. I just uploaded what I had and we've developed on it since. I hadn't really considered what files were actually prudent or not.

even deleting the folder, it is in git history, this repo is still because of that

there are tools to delete things in bulk from the git history, better see

**Pull request merged**
